### ISSUE TITLE
Write an explainer for the design

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-intl-relative-time#22]
There's been a lot written about RelativeTimeFormat, but it's scattered in a few different places. We should collect everything in a single README. The explainer should get at the main points of motivation for this design, including:
- Why this is the right level of abstraction
- Why did we make the main API choices that we made
- Why is this in terms of numbers, rather than dates/duration

**Comment by rxaviers** [comment]
Very good point

**Comment by caridy** [comment]
https://github.com/caridy/proposal-intl-relative-time/pull/29
