### ISSUE TITLE
The rendered spec does not match the spec text that's checked in

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-intl-relative-time#24]
For example, the rendered spec text includes a default unit ("second"), whereas the spec source does not.

Maybe we should also keep the rendering on gh-pages, so it can be updated with a PR rather than going to that externally hosted page.

**Comment by rxaviers** [comment]
Let's see what @caridy things, but I'm :+1:

**Comment by rxaviers** [comment]
thinks*

**Comment by caridy** [comment]
it is now up to date.
