### ISSUE TITLE
Reconsider style names

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-intl-relative-time#41]
Names are currently "long", "short" and "narrow". Why not medium in the middle? Where do they come from? This was raised at the July 2017 TC39 meeting. (cc @msaboff)

**Comment by zbraniecki** [comment]
Because only those three are supported by CLDR which we took as an example: http://www.unicode.org/cldr/charts/31/summary/fr.html#1440

I'm not sure if there is any internationalization database which has `medium`. Do you have an example?

**Comment by caridy** [comment]
I think the concern was mostly to align with the OS/host, and how they treat this values today. But I do agree with that `"medium"` is a weird term from the API point of view, and the fact that we do have some prior art in 402 for those 3 possible values.

**Comment by littledan** [comment]
OK, I was speculating that these were the values in CLDR, but I couldn't find the right reference while I was giving the presentation.

Aligning with CLDR seems like a strong reason to me. Any more thoughts?

**Comment by rxaviers** [comment]
You did a good job, I thought you were pretty confident about it :)🙈.

On [UTS#35](http://www.unicode.org/reports/tr35/tr35-dates.html#Calendar_Fields), the **long** form is implicit, while the other two forms (**short** and **narrow**) are cited. It also says "**narrow** may be ambiguous out of context".

**Comment by littledan** [comment]
@msaboff brought this up again at the September 2017 TC39 meeting, saying that medium is used by both Windows and Mac OS date formatters as a length. Would it really not make sense to do this sort of change? Does anyone know about other relative time formatters, besides ICU/CLDR?

**Comment by zbraniecki** [comment]
How does Apple map `medium` to CLDR?

**Comment by littledan** [comment]
OK, until I hear more examples of libraries that @msaboff's suggested names for relative time formatting libraries, I'll leave the specification as it is.

**Comment by wopian** [comment]
The current names are also consistent with the parameters of the [Intl.DateTime] API. 

[Intl.DateTime]:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Parameters

**Comment by icambron** [comment]
+1 for keeping the names as they are for consistency with the Intl.DateTime API. IMO, "short" and "narrow" are good names, whereas "long" and "medium" are not; it's not the relative sizes the matter, but rather the degree of abbreviation. So they should have called it "full" instead of "long". But I think that ship sailed long ago.

**Comment by littledan** [comment]
OK, we've settled on keeping these names and moved to Stage 3 on that basis.
