### ISSUE TITLE
What is relativeTimeFormat.[[Locale]] used for?

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-intl-relative-time#64]

**Comment by littledan** [comment]
http://tc39.github.io/proposal-intl-relative-time/#sec-Intl.RelativeTimeFormat.prototype.resolvedOptions

We are thinking of rewriting these in an imperative style which uses square brackets. I think @anba has a patch. For now, this proposal mimics the style of the current specification.

**Comment by anba** [comment]
The `resolvedOptions` methods in ECMA-402 were already changed to use an imperative style.

**Comment by littledan** [comment]
Oh, sounds like it is time to change this. Anybody want to contribute a patch?
