### ISSUE TITLE
Review @@toStringTag value

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-intl-relative-time#72]
> 1.4.2 Intl.RelativeTimeFormat.prototype[ @@toStringTag ]
>
> The initial value of the @@toStringTag property is the string value "Object". 

Why? What is even the point of having the property if you're going to make it say "Object"?

**Comment by anba** [comment]
As mentioned in https://github.com/tc39/proposal-intl-locale/issues/44, we should try to be consistent with `@@toStringTag` in the newer Intl proposals.

Also see https://github.com/tc39/ecma402/issues/176
