### ISSUE TITLE
"an optional argument value"

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-intl-relative-time#73]
>  When the Intl.RelativeTimeFormat.prototype.format is called with an optional argument value, the following steps are taken: 

>  When the Intl.RelativeTimeFormat.prototype.formatToParts is called with an optional argument value, the following steps are taken: 

Both of these methods have two required arguments, rather than a single optional one.

**Comment by littledan** [comment]
That's right, this was some poor copypasta. PRs welcome.
