### ISSUE TITLE
Create options objects with null proto

### ISSUE THREAD

**Issue by gsathya** [tc39/proposal-intl-relative-time#76]
In [InitializeRelativeTimeFormat](https://tc39.github.io/proposal-intl-relative-time/#sec-InitializeRelativeTimeFormat), we have: 
> 22. Let nfOptions be ObjectCreate(%ObjectPrototype%).

and 

> 27. Let prOptions be ObjectCreate(%ObjectPrototype%).

If we could instead change these to `ObjectCreate(null)`, that would reduce observable behavior that the engine could optimize out.

**Comment by littledan** [comment]
Thanks for pointing this out. We actually transitioned the other ECMA-402 options processing to use `null` in a related context in https://github.com/tc39/ecma402/pull/170 ; we shouldn't introduce a new place for things on `Object.prototype` to pollute internally-generated options bags.

PRs welcome. @Ms2ger would you be interested in writing a PR? We should have tests which cover the final semantics.
