### ISSUE TITLE
isFinite() does not seem to be formally defined

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-intl-relative-time#86]
> 1.1.3 PartitionRelativeTimePattern ( relativeTimeFormat, value, unit )
>
> 4. If isFinite(value) is false, then throw a RangeError exception.

I can guess what it means, but it doesn't seem to be defined.

**Comment by littledan** [comment]
In ECMA-262, we usually check for the three nonfinite values, e.g., https://tc39.github.io/ecma262/#sec-isfinite-number . I'd suggest doing the same here. PRs welcome!
