### ISSUE TITLE
PartitionRelativeTimePattern accepts non-time values

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-relative-time#95]
The preamble in [PartitionRelativeTimePattern](http://tc39.github.io/proposal-intl-relative-time/#sec-PartitionRelativeTimePattern) states that:
> [...] value (interpreted as a time value as specified in ES2016, 20.3.1.1) [...]

but `value` is not actually restricted to a time value. (And we probably don't want to restrict it to a time value to support fractional values.)

**Comment by littledan** [comment]
That's right! OK, editorial PRs welcome to clarify that it's treated as a numeric value.
